image: node:8.1.4

stages:
  - lint
  - test

lint_tests:
  stage: lint
  cache:
     paths:
       - /usr/local/lib/node_modules/
  before_script:
    - npm install standard -g
  script:
    - standard src || exit 1
  
mocha_tests:
  stage: test
  services:
    - redis
  cache:
    paths:
      - /usr/local/lib/node_modules/
      - node_modules/
  before_script:
    - npm install 
    - npm install mocha -g
    - wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    - apt-get update && apt-get install -y unzip
    - unzip ngrok.zip
    - ./ngrok authtoken $NGROK_AUTH_TOKEN
    - ./ngrok http 8000 -subdomain=$NGROK_SUBDOMAIN &
    - node main.js &
  script:
    - npm test
