image: node:8.1.4

stages:
  - standardjs
  - mocha

cache:
  paths:
    - node_modules/

standardjs:
  stage: standardjs
  before_script:
    - npm install standard
  script:
    - node node_modules/standard/bin/cmd.js src || exit 1
  
mocha:
  stage: mocha
  services:
    - redis
  before_script:
    - npm install 
    - npm install mocha
    - wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    - apt-get update && apt-get install -y unzip
    - unzip ngrok.zip
    - ./ngrok authtoken $NGROK_AUTH_TOKEN
    - ./ngrok http 8000 -subdomain=$NGROK_SUBDOMAIN &
    - export ALLOW_PUBLIC_API=true
    - export SILENT_START=true
    - export REDIS_URL=redis://redis:6379
    - export NODE_ENV=testing
    - node main.js &
  script:
    - node node_modules/.bin/mocha src --recursive --timeout 180000 --slow 180000
