language: node_js

node_js:
  - "8.1.4"
  
services: redis-server

branches:
  only:
   - release

before_script:
   - npm install standard
   - npm install mocha
   - wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
   - unzip ngrok.zip
   - ./ngrok authtoken $NGROK_AUTH_TOKEN
   - ./ngrok http 8000 &
   - node main.js &

script: 
   - node node_modules/standard/bin/cmd.js backend core || exit 1
   - npm test

cache:
  directories:
    - node_modules
