language: node_js

node_js:
  - "8.1.4"
  
services: redis-server

branches:
  only:
   - release

before_script:
   - npm install standard
   - npm install mocha

script: 
   - node node_modules/standard/bin/cmd.js backend core || exit 1
   - npm test

cache:
  directories:
    - node_modules
