# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:8.1.4
      - image: redis
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: npm install
      
      - run: npm install -g mocha
      
      - run: npm install -g standard
      
      - run: wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      
      - run: unzip ngrok.zip
      
      - run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      
      - run: ./ngrok http 8000 -subdomain=$NGROK_SUBDOMAIN &
      
      - run: node main.js &
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: node --version
      
      - run: npm --version
    
      - run: node node_modules/standard/bin/cmd.js backend core || exit 1
      
      - run: npm test
