name: test-and-publish

on: [push]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.4]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 1
    - name: Set up as module
      run: |
        HERE=`pwd`
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        npm install @userdashboard/dashboard --no-save
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install ngrok faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/stripe-subscriptions @userdashboard/storage-redis
        npm install -g mocha standard
        rm node_modules/@userdashboard/stripe-subscriptions/*.js
        rm -rf node_modules/@userdashboard/stripe-subscriptions/src 
        cp /home/runner/work/stripe-subscriptions/stripe-subscriptions/*.js node_modules/@userdashboard/stripe-subscriptions
        cp -R /home/runner/work/stripe-subscriptions/stripe-subscriptions/src/ node_modules/@userdashboard/stripe-subscriptions/src/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/stripe-subscriptions\"\] \}}
        echo $PACKAGE > package.json
    - name: Lint (standard.js)
      run: standard src
    - name: Test (redis)
      run: |
        mocha --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/stripe-subscriptions/**/{,!(public)}/*.test.js" | tee /home/runner/work/stripe-subscriptions/stripe-subscriptions/tests.txt
        TESTS=`cat /home/runner/work/stripe-subscriptions/stripe-subscriptions/tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
      working-directory: '/tmp/project'
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_1 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_1 }}
        STRIPE_JS: false
        SUBSCRIPTION_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
        DISABLE_PAYOUT_TESTS: "true"
        GENERATE_RESPONSE: true
        GENERATE_SCREENSHOTS: true
        RESPONSE_PATH: "/home/runner/work/stripe-subscriptions/stripe-subscriptions/documentation"
        SCREENSHOT_PATH: "/home/runner/work/stripe-subscriptions/stripe-subscriptions/documentation/screenshots"
        SCREENSHOT_LANGUAGES: "en"
    - name: Generate supporting texts
      run: node main.js
      working-directory: /home/runner/work/stripe-subscriptions/stripe-subscriptions/
      env:
        NODE_ENV: sitemap
        EXIT_ON_START: true
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STRIPE_KEY: ${{ secrets.STRIPE_KEY_1 }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_1 }}
        STRIPE_JS: false
        SUBSCRIPTION_WEBHOOK_ENDPOINT_SECRET: "replaced-at-runtime"
        NGROK: true
        DISABLE_PAYOUT_TESTS: "true"
    - name: Publish to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - name: Publish documentation assets
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: "userdashboard/userdashboard.github.io"
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        publish_dir: documentation
        keep_files: true
        publish_branch: master
